jobs:
  include:
    - language: go
      go: "1.10"
      script: go test ./go

    - language: java
      jdk: openjdk11
      install: skip
      before_script: cd java
      script: ./mvnw test

    - language: node_js
      node_js: 4.0
      script: npm test

    - language: python
      python: 3.4
      install:
        - pip install -U pip
        - pip install -U pytest
      before_script: cd python
      script: python -m pytest

    - language: ruby
      rvm: 2.0
      script: ruby ruby/lib/any_ascii_test.rb

    - language: rust
      rust: "1.20.0"
      before_script: cd rust
      script: cargo test
