jobs:
  include:
    - language: go
      go: "1.10"
      install: skip
      script: go test ./go

    - language: java
      jdk: openjdk11
      install: skip
      before_script: cd java
      script: ./mvnw test

    - language: node_js
      node_js: 4.0
      install: skip
      script: npm test

    - language: python
      python: 3.4
      install: skip
      before_script: cd python
      script: python -m pytest

    - language: ruby
      rvm: 2.0
      install: skip
      script: ruby ruby/lib/any_ascii_test.rb

    - language: rust
      rust: "1.36.0"
      install: skip
      before_script: cd rust
      script: cargo test

    - language: csharp
      mono: none
      dotnet: "3.1.100"
      solution: csharp/AnyAscii.sln
      install: skip
      before_script: cd csharp/test
      script: dotnet test

    - language: sh
      script: ./sh/test.sh

    - language: php
      php: '5.6'
      install: skip
      script: php php/test.php
