[package]
name = "any_ascii"
version = "0.1.6"
authors = ["Hunter WB <hunter@hunterwb.com>"]
homepage = "https://anyascii.com"
repository = "https://github.com/hunterwb/any-ascii"
description = "Unicode to ASCII transliteration"
license = "ISC"
categories = ["text-processing", "internationalization"]
keywords = [
  "unicode",
  "ascii",
  "transliteration",
  "emoji",
  "unidecode"
]
readme = "../README.md"

[[bin]]
name = "anyascii"
path = "src/main.rs"

[badges]
travis-ci = { repository = "hunterwb/any-ascii" }
